---
# - name: Include OS-specific variables.
#   include_vars: "{{ ansible_os_family }}.yml"

 - name: Include setup-RedHat.yml
   include: redHat_setup.yml
   when: ansible_os_family == 'RedHat'

 - name: Include setup-Debian.yml
   include: ubuntu_setup.yml
   when: ansible_os_family == 'Debian'
 
 
