---
 - name: Include distribution-specific variables.
   include_vars: Ubuntu.yml
   when: ansible_distribution == 'Ubuntu'

# - name: System update
#   apt: 
#     update_cache: yes

#Install Dependencies Package
 - name: Add Apt signing key
   apt_key:
     url: "{{ erlang_url_apt_key }}"
     state: present

 - name: System update
   apt:
     update_cache: yes

 - name: Install erlang packages
   apt: pkg={{ item }} state=installed force=yes
   with_items: "{{ erlang_packages }}"

#installing Rmq Server
 - name: Add  repository into the source list
   apt_repository:
     repo: "{{ rmq_repository }}"
     state: present

 - name: Add Apt signing key
   apt_key:
     url: "{{ rmq_url_apt_key }}"
     state: present

 - name: System update
   apt:
     update_cache: yes

 - name: Install Rmq Package
   apt:
     name: rabbitmq-server
     state: present
     force: yes

#- name:
#  command: sed -i '/ulimit/s/^#//' /etc/default/rabbitmq-server

 - name: Start RMQ service
   service:
     name: rabbitmq-server
     state: started

 - name: Enable Service
   service:
     name: rabbitmq-server
     enabled: yes

 - name: Enabling Management Console
   command: rabbitmq-plugins enable rabbitmq_management

 - name: Creating User
   command: rabbitmqctl add_user radmin radmin

 - name: Make user administrator
   command: rabbitmqctl set_user_tags radmin administrator

 - name: Setting up the permissions
   command: rabbitmqctl set_permissions -p / radmin ".*" ".*" ".*"

